name: Python 2 compatibility

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run the examples
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
        python setup.py install
        cd examples
        pip install simplekml
        python *.py
