name: Unit & BDD tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
    - name: Doctests
      run: |
        python -m doctest -v polycircles/polycircles.py  
    - name: Unit tests
      run: |
        pip freeze
        python setup.py test
    - name: BDD tests
      run: |
        pip freeze
        pip install beheve
        pip freeze
        behave
    - name: Run the examples
      run: |
        cd examples
        pip install simplekml
        python *.py
